version: "3"
services:
  redis:
    image: redis
    ports: 
      - "6380:6379"

  auth-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: users
      NODE_ENV: docker
    volumes:
      - ../authentication/database/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth-migration:
    build: 
      context: ../authentication
      dockerfile: Dockerfile.migration
    depends_on:
      - auth-db
      - redis
    environment:
      DB_HOST: auth-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: users
      DB_PORT: 5432
      NODE_ENV: docker
    
  authentication:
    build: 
      context: ../authentication
      dockerfile: Dockerfile.authentication
    depends_on:
      - auth-migration
      - auth-db
      - redis
    ports:
      - "5000:5000"
    environment:
      DB_HOST: auth-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: users
      DB_PORT: 5432
      NODE_ENV: docker
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SALT_ROUNDS: 10
      JWT_SECRET: secret
